version: "3"
services:
  node-app:
    container_name: node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=reference
    env_file:
      - ./.env
